package com.rands.couponproject.utils;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class DBUtils {
	
	/**
	 * getGeneratedKey - use this method after INSERT to retrieve the auto generated id of the inserted row.
	 * @param ps - an executed PreparedStatement
	 * @return - the id of the 1st affected row
	 * @throws SQLException 
	 */
	public static long getGeneratedKey(PreparedStatement ps) throws SQLException {
		
        try (ResultSet generatedKeys = ps.getGeneratedKeys()) { // get all the keys that were generated by ps 
            if (generatedKeys.next()) {
            	long id = generatedKeys.getLong(1); // for an insert sql statement  there will be one key
            	return id;
            }
            else {
                throw new SQLException("generatedKeys could not be obtained.");
            }
        }		
		
	}
}
